# Generated by Django 4.0.5 on 2022-06-16 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=10, verbose_name='Genero')),
                ('nroTelefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.categoria', verbose_name='Telefono')),
            ],
        ),
    ]
