# Generated by Django 3.2.8 on 2022-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0004_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
