# Generated by Django 3.2.8 on 2022-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0005_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nroTelefono',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
