# Generated by Django 4.0.5 on 2022-06-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0006_auto_20220617_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=50, null='True', verbose_name='Correo'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, null='True', verbose_name='Direccion'),
            preserve_default='True',
        ),
    ]
