# Generated by Django 4.0.5 on 2022-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0007_remove_cliente_edad_remove_cliente_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=20, null='True', verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20, null='True', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nroTelefono',
            field=models.CharField(max_length=15, null='True', verbose_name='Telefono'),
        ),
    ]
