# Generated by Django 4.0.5 on 2022-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0008_alter_cliente_apellido_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo'),
        ),
    ]
