# Generated by Django 4.0.5 on 2022-07-06 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iniv', '0010_alter_cliente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='Nombre cliente')),
                ('apellidoCliente', models.CharField(max_length=20, verbose_name='Apellido cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('totalCompra', models.IntegerField(verbose_name='Total de compra')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de compra')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=50, null='True', verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.producto', verbose_name='codigo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('totalCompra', models.IntegerField(verbose_name='Total de compra')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.producto', verbose_name='codigo')),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.compra', verbose_name='id compra')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.cliente', verbose_name='Rut  cliente')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniv.cliente', verbose_name='Rut cliente'),
        ),
    ]
